#!/bin/sh
# From Gerrit Code Review 3.2.3
#
# Part of Gerrit Code Review (https://www.gerritcodereview.com/)
#
# Copyright (C) 2009 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Description :
# -----------------------------------------------------
# The file has been updated to connect commits to Deck cards
#
# 2025 hossjava@osxx.com

# avoid [[ which is not POSIX sh.
if test "$#" != 1 ; then
  echo "$0 requires an argument."
  exit 1
fi

if test ! -f "$1" ; then
  echo "file does not exist: $1"
  exit 1
fi

#---------------------------------------
# Import default settings and message formater
GIT_ROOT="$(git rev-parse --show-toplevel)"
GITHOOK_DEFAULT_FILE="$GIT_ROOT/.gitdefault"
if [ -f "$GITHOOK_DEFAULT_FILE" ]; then
    . "$GITHOOK_DEFAULT_FILE"
else
    deckLinkFlag=false
    gerritChangeIdFlag=true
    commitCheckFlag=true
fi

COMMIT_MSG_DIRECTIVES_SHINC=.git/hooks/commit-msg-directives.shinc
if [ -f "$COMMIT_MSG_DIRECTIVES_SHINC" ]; then
    . ${COMMIT_MSG_DIRECTIVES_SHINC}

    COMMIT_MSG_FORMAT_SHINC=.git/hooks/commit-msg-format.shinc
    if [ -f "$COMMIT_MSG_FORMAT_SHINC" ]; then
        . ${COMMIT_MSG_FORMAT_SHINC}
    fi
fi
#---------------------------------------

if [ "$gerritChangeIdFlag" = true ]; then
    # Do not create a change id if requested
    if test "false" = "`git config --bool --get gerrit.createChangeId`" ; then
        exit 0
    fi
fi

# $RANDOM will be undefined if not using bash, so don't use set -u
random=$( (whoami ; hostname ; date; cat $1 ; echo $RANDOM) | git hash-object --stdin)
dest="$1.tmp.${random}"

trap 'rm -f "${dest}"' EXIT

if ! git stripspace --strip-comments < "$1" > "${dest}" ; then
    echo "cannot strip comments from $1"
    exit 1
fi

if test ! -s "${dest}" ; then
    echo "file is empty: $1"
    exit 1
fi

#---------------------------------------
# Import Deck link adder
COMMIT_MSG_DECKLINK_SHINC=.git/hooks/commit-msg-decklink.shinc
if [ -f "$COMMIT_MSG_DECKLINK_SHINC" ]; then
    . ${COMMIT_MSG_DECKLINK_SHINC}
fi
#---------------------------------------

if [ "$gerritChangeIdFlag" = true ]; then
    # Avoid the --in-place option which only appeared in Git 2.8
    # Avoid the --if-exists option which only appeared in Git 2.15
    if ! git -c trailer.ifexists=doNothing interpret-trailers \
          --trailer "Change-Id: I${random}" < "$1" > "${dest}" ; then
        echo "cannot insert change-id line in $1"
        exit 1
    fi

    if ! mv "${dest}" "$1" ; then
        echo "cannot mv ${dest} to $1"
        exit 1
    fi
fi
